# Generated by Django 5.0.4 on 2024-05-15 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPersons',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('related_person_type', models.CharField(choices=[('AS', 'Asistente'), ('BR', 'Hermano'), ('SO', 'Hijo(a)'), ('CO', 'Pareja'), ('FA', 'Padre'), ('FR', 'Amigo(a)'), ('SU', 'Supervisor'), ('MO', 'Madre'), ('PA', 'Socio'), ('RE', 'Recomendación'), ('FY', 'Familiar'), ('SI', 'Hermana'), ('SP', 'Conyuge'), ('OT', 'Otro')], default='FR', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
