# Generated by Django 5.0.4 on 2024-05-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='last_nmae',
            new_name='last_name',
        ),
    ]
