# Generated by Django 5.0.4 on 2024-05-15 03:49

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_type', models.CharField(choices=[('MO', 'Móvil'), ('WO', 'Trabajo'), ('HO', 'Casa'), ('MA', 'Principal'), ('WF', 'Fax laboral'), ('HF', 'Fax de casa'), ('LO', 'Localizador'), ('OT', 'Otro')], default='MO', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
